# Generated by Django 2.0.2 on 2018-03-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=40)),
                ('pinyin', models.CharField(max_length=200)),
                ('translation', models.CharField(max_length=800)),
            ],
            options={
                'ordering': ('word',),
            },
        ),
    ]
